baseURL = "https://example.com/"
languageCode = "en-us"
title = "hugonews example site"

[module]
  [[module.imports]]
    path = "github.com/spaghettiwews/hugonews"

[taxonomies]
    tag = "tags"
    category = "categories"
    site = "sites"
