languageCode = "en-us"
title = "hugonews example site"
baseURL = "https://example.com/"
#theme = "hugonews"

#[module]
#  [[module.imports]]
#    #path = "github.com/spaghettiwews/hugonews"
#    path = "github.com/gohugoio/gohugoioTheme"    

[taxonomies]
    tag = "tags"
    category = "categories"
    site = "sites"
