name: StaticGen

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Build & Deploy to GitHub Pages
      with:
        REMOTE_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: yurikoval/middleman-gh-pages-action@master


    #- 
    #  name: Generate Site
    #  uses: crazy-max/ghaction-hugo@v1
    #  with:
    #    version: latest
    #    extended: false
    #    args: --cleanDestinationDir --minify --verbose
    #-
    #  name: Publish Pages
    #  if: success() 
    #  with:
    #    target_branch: gh-pages
    #    build_dir: public
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  uses: crazy-max/ghaction-github-pages@v2
