name: StaticGen

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Build & Deploy to GitHub Pages
      with:
        REMOTE_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: yurikoval/middleman-gh-pages-action@master

